version: '3.8'

networks:
  data_handler_network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
      - data_handler_network

  backend:
    build: .
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - data_handler_network
#  celery:
#    build: .
#    command: celery -A celery_app.celery_conf worker --loglevel=INFO
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
#      - db
#    networks:
#      - data_handler_network
#
#  celery_beat:
#    build: .
#    command: celery -A celery_app.celery_conf beat --loglevel=INFO
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
#      - db
#    networks:
#      - data_handler_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - data_handler_network

  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/user_conf.d:ro
      - .:/app
    depends_on:
      - backend
    networks:
      - data_handler_network


volumes:
  db_data:
  redis_data:
